--- #YAML:1.0
name:                Test-Program
version:             0.10
abstract:            Testing tools for Perl programs
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Exporter:                      0
    Test::Builder::Tester:         0
    Test::More:                    0
    Test::Pod:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Lester <andy@petdance.com>
